config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get '/login', to: 'sessions#login'
  get '/logout', to: 'sessions#logout'

  resources :users, only: [:new]
    get '/users/:id/dashboard', to: 'users/dashboard#index', as: :dashboard
    get '/users/:id/image/new', to: 'users/images#new', as: :new_user_image
    post '/users/:id/image/new', to: 'users/images#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user

  validates_presence_of :title, 
                        :image_url
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password 

  has_many :images 

  validates_presence_of :name, 
                        :email 

  validates_uniqueness_of :email 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
       session[:user_id] = user.id 
       flash[:success] = "Welcome to your Dashboard, #{user.name}"

       redirect_to dashboard_path(user)
    else 
      flash[:error] = "Invalid Credentials, please try again"
      redirect_to root_path
    end
  end

  def logout 
    session.delete(:user_id)
    flash[:notice] = "You have been logged out"
    redirect_to root_path
  end
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < ApplicationController 

  def index 
    @images = current_user.images 
  end
end

app/controllers/users/images_controller.rb
class Users::ImagesController < ApplicationController 

  def new 
    @image = Image.new
  end

  def create
    @user = User.find(params[:id])
    @image = @user.images.new(image_params)
    @image.save
    flash[:notice] = "#{@image.title} was created"
    redirect_to dashboard_path(current_user)
  end

  private 

  def image_params 
    params.require(:image).permit(:title, :description, :image_url)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController 
  def index 
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |name, msg|%>
    <h3><%= msg %></h3>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/dashboard/index.html.erb
<h3 align="center"><%= button_to 'Logout', logout_path, method: :get %></h3>

<h1 align="center"> Welcome to your Dashboard <%= current_user.name %> </h1>

<h3 align="center"><%= button_to 'Add New Image', new_user_image_path(current_user), method: :get %></h3>

<h2 align="center"> All My Images </h2>
<div align="center">
<h3> <% @images.each do |image| %> </h3>
<section id=image-<%= image.id %> >
  <h4>Image Title: <%= image.title %></h4>
  <p>Description: <%= image.description %></p>
  <%= image_tag("#{image.image_url}", size: "300") %><br>
  </section>
<% end %><br>

app/views/users/images/new.html.erb
<h1 align="center">Upload a New Image</h1>

<div align="center">
<%= form_with url: new_user_image_path(current_user), model: @image, method: :post, local: true do |f|%>
    <%= f.label :title, "Title: " %><br>
    <%= f.text_field :title %><br><br>

    <%= f.label :description, "Description: " %><br>
    <%= f.text_field :description %><br>

    <%= f.label :image_url, "Image URL: " %><br>
    <%= f.text_field :image_url %><br>

    <%= f.submit "Upload Image" %>
<% end %>
</div>

app/views/welcome/index.html.erb
<div class='jumbotron jumbotron-fluid'>
  <div class='container'>
    <h1 class='display-4'>Welcome to Image Manager</h1>
    <p class='lead'>This is an application to explore and upload images! Please login to use the app </p>
  </div>
</div> 

<%= form_with url: login_path, method: :get, local: true do |f|%>
    <%= f.label :email, 'Email' %>
    <%= f.email_field :email %>
    <%= f.label :password, 'Password' %>
    <%= f.password_field :password %><br/><br/>
    <%= f.submit "Login" %>
<% end %>